---
namespace-config:
  - 0.1.0 Initial Chart
  - 0.1.1 Grant access to existing PodSecurityPolicy
  - 0.1.2 Rmove PodSecurityPolicy
  - 0.1.3 Update Chart.yaml apiVersion to v2
  - 2024.2.0 Update version to align with the Openstack release cycle
...
