---
prometheus-blackbox-exporter:
  - 0.1.0 Initial Chart
  - 0.1.1 Change helm-toolkit dependency version to ">= 0.1.0"
  - 0.1.2 Rename image key name
  - 0.1.3 Update htk requirements
  - 0.1.4 Fix indentation
  - 0.1.5 Added OCI registry authentication
  - 0.1.6 Update Chart.yaml apiVersion to v2
  - 2024.2.0 Update version to align with the Openstack release cycle
...
