---
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

release_group: null

labels:
  agent:
    node_selector_key: openstack-network-node
    node_selector_value: enabled
  job:
    node_selector_key: openstack-control-plane
    node_selector_value: enabled

images:
  tags:
    ovn_bgp_agent: ghcr.io/fivetime/openstackhelm/ovn-bgp-agent:master-ubuntu_noble
    frr: quay.io/frrouting/frr:10.4.1
    frr_exporter: docker.io/tynany/frr_exporter:v1.8.1
    dep_check: quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_jammy
    image_repo_sync: docker.io/docker:28.1.1
  pull_policy: IfNotPresent
  local_registry:
    active: false
    exclude:
      - dep_check
      - image_repo_sync

# OVN BGP Agent configuration
conf:
  ovn_bgp_agent:
    DEFAULT:
      debug: false
      use_stderr: true
      use_syslog: false
      bgp_nic: bgp-nic
      bgp_vrf: bgp-vrf
      bgp_vrf_table_id: 10
      reconcile_interval: 120
      # Options: underlay | vrf | ovn
      exposing_method: 'underlay'
      # Options: ovn_bgp_driver, nb_ovn_bgp_driver, ovn_evpn_driver, ovn_stretched_l2_bgp_driver
      driver: ovn_bgp_driver
      anycast_evpn_gateway_mode: false
      # OVS connection
      ovsdb_connection: unix:/run/openvswitch/db.sock
      ovsdb_connection_timeout: 180
      # Expose options
      expose_tenant_networks: false
      expose_ipv6_gua_tenant_networks: true
      require_snat_disabled_for_tenant_networks: false
      address_scopes: ""
    local_ovn_cluster:
      bgp_chassis_id: 'bgp'
      external_nics: ['eth1', 'eth2']
      ovn_nb_connection: 'unix:/run/ovn/ovnnb_db.sock'
      ovn_sb_connection: 'unix:/run/ovn/ovnsb_db.sock'
    privsep:
      helper_command: "sudo /install/local/bin/privsep-helper"

# BGP configuration
bgp:
  enabled: true

  # IPv4 Unicast BGP Peering (to Leaf Switch)
  # peer_ip options:
  #   "" or "detection" - Auto-detect (route table -> ARP -> first IP)
  #   "first"            - Use first IP in subnet (network + 1)
  #   "last"             - Use last IP in subnet (broadcast - 1)
  #   "10.0.192.1"       - Fixed IP address
  peer_ip: ""

  # Enable IPv6 Dual-Stack BGP
  # When enabled, establishes separate BGP sessions:
  #   - IPv4 session: exchanges IPv4 routes
  #   - IPv6 session: exchanges IPv6 routes
  # Requirements:
  #   - br-ex must have IPv6 address configured
  #   - Leaf switch must support dual-stack BGP
  #   - ipv6 must be configured in ToR for each subnet
  ipv6:
    enabled: true

  # Leaf Switch Configuration Mapping
  # This configuration is only used during initial helm install.
  # After installation, the mapping is stored in a ConfigMap that can be
  # edited directly without triggering pod restarts.
  #
  # Format per subnet:
  #   "subnet_cidr":
  #     asn: "Leaf BGP AS Number"
  #     ipv4: "IPv4 Gateway Address" (required)
  #     ipv6: "IPv6 Gateway Address" (required if ipv6.enabled=true)
  #     desc: "Human readable description" (optional)
  #
  # The subnet is matched against the br-ex interface's subnet.
  # Example: If br-ex has 10.0.192.115/20, it will match "10.0.192.0/20"
  tors:
    "10.0.192.0/20":
      asn: "4200000100"
      ipv4: "10.0.192.1"
      ipv6: "fd00:1:2:3::1"
      desc: "Rack-1"
    "10.0.208.0/20":
      asn: "4200000100"
      ipv4: "10.0.208.1"
      ipv6: "fd00:1:2:4::1"
      desc: "Rack-2"

  # EVPN Configuration
  evpn:
    enabled: false
    # Route Reflector IP
    rr_ip: "172.17.0.0"
    # Route Reflector ASN
    rr_asn: "4200000000"

# Networking
network:
  # Host paths
  host:
    openvswitch_db: /run/openvswitch
    ovn: /run/ovn

monitoring:
  enabled: false

pod:
  security_context:
    ovn_bgp_agent:
      pod:
        runAsUser: 0
        fsGroup: 0
      container:
        ovn_bgp_agent:
          runAsUser: 0
          privileged: true
          readOnlyRootFilesystem: false
        frr:
          runAsUser: 0
          privileged: true
          readOnlyRootFilesystem: false
        ovn_northd:
          runAsUser: 0
          privileged: true
          readOnlyRootFilesystem: false
        ovn_controller:
          runAsUser: 0
          privileged: true
          readOnlyRootFilesystem: false
        init_local_ovn:
          runAsUser: 0
          privileged: true
          readOnlyRootFilesystem: false
        init_frr_config:
          runAsUser: 0
          privileged: true
          readOnlyRootFilesystem: false

  tolerations:
    ovn_bgp_agent:
      enabled: false
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  mounts:
    ovn_bgp_agent:
      ovn_bgp_agent:
        volumeMounts: []
        volumes: []
      frr:
        volumeMounts: []
        volumes: []
      ovn_northd:
        volumeMounts: []
        volumes: []
      ovn_controller:
        volumeMounts: []
        volumes: []

  lifecycle:
    upgrades:
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        ovn_bgp_agent:
          enabled: true
          min_ready_seconds: 0
          max_unavailable: 1
    termination_grace_period:
      ovn_bgp_agent:
        timeout: 30

  probes:
    ovn_bgp_agent:
      ovn_northd:
        readiness:
          enabled: true
          params:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
        liveness:
          enabled: true
          params:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
      ovn_controller:
        readiness:
          enabled: true
          params:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
        liveness:
          enabled: true
          params:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
      ovn_bgp_agent:
        readiness:
          enabled: true
          params:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
        liveness:
          enabled: true
          params:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
      frr:
        readiness:
          enabled: true
          params:
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
        liveness:
          enabled: true
          params:
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3

  resources:
    enabled: false
    ovn_bgp_agent:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    frr:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "2000m"
    ovn_northd:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    ovn_controller:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    init:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    jobs:
      image_repo_sync:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs:
          - ovn-bgp-agent-image-repo-sync
        services:
          - endpoint: node
            service: local_image_registry
  static:
    ovn_bgp_agent:
      jobs:
        - ovn-ovsdb-nb-bootstrap
      services:
        - endpoint: internal
          service: ovn_nb
        - endpoint: internal
          service: ovn_sb
    image_repo_sync:
      services:
        - endpoint: internal
          service: local_image_registry

# Endpoints
endpoints:
  cluster_domain_suffix: cluster.local
  local_image_registry:
    name: docker-registry
    namespace: docker-registry
    hosts:
      default: localhost
      internal: docker-registry
      node: localhost
    host_fqdn_override:
      default: null
    port:
      registry:
        node: 5000
  ovn_nb:
    namespace: null
    hosts:
      default: ovn-ovsdb-nb
    host_fqdn_override:
      default: null
    port:
      nb:
        default: 6641
  ovn_sb:
    namespace: null
    hosts:
      default: ovn-ovsdb-sb
    host_fqdn_override:
      default: null
    port:
      sb:
        default: 6642

# Manifests control
manifests:
  configmap_bin: true
  configmap_etc: true
  configmap_asn: true
  priorityclass: true
  networkpolicy: false
  serviceaccount: true
  service_metrics: true
  job_image_repo_sync: true
  poddisruptionbudget: true
  daemonset_ovn_bgp_agent: true