---
pod:
  security_context:
    exporter:
      container:
        kube_state_metrics:
          appArmorProfile:
            type: RuntimeDefault
    kubernetes_entrypoint:
      container:
        kubernetes_entrypoint:
          appArmorProfile:
            type: RuntimeDefault
...
