{{/*
Licensed under the Apache License, Version 2.0 (the "License");
*/}}

{{- if .Values.manifests.deployment_proxy }}
{{- $envAll := . }}

{{- $serviceAccountName := "nexus-proxy" }}
{{ tuple $envAll "proxy" $serviceAccountName | include "helm-toolkit.snippets.kubernetes_pod_rbac_serviceaccount" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-proxy
  labels:
{{ tuple $envAll "nexus" "proxy" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  replicas: {{ .Values.pod.replicas.proxy }}
  selector:
    matchLabels:
{{ tuple $envAll "nexus" "proxy" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "nexus" "proxy" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 8 }}
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
{{ dict "envAll" $envAll "application" "proxy" | include "helm-toolkit.snippets.kubernetes_pod_security_context" | indent 6 }}
      affinity:
{{ tuple $envAll "nexus" "proxy" | include "helm-toolkit.snippets.kubernetes_pod_anti_affinity" | indent 8 }}
      nodeSelector:
        {{ .Values.labels.proxy.node_selector_key }}: {{ .Values.labels.proxy.node_selector_value | quote }}
{{- if .Values.pod.tolerations.proxy.enabled }}
{{ tuple $envAll "proxy" "proxy" | include "helm-toolkit.snippets.kubernetes_tolerations" | indent 6 }}
{{- end }}
      initContainers:
{{ tuple $envAll "proxy" list | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: proxy
{{ tuple $envAll "proxy" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.proxy | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
{{ dict "envAll" $envAll "application" "proxy" "container" "proxy" | include "helm-toolkit.snippets.kubernetes_container_security_context" | indent 10 }}
          ports:
            - name: http
              containerPort: {{ .Values.proxy.ports.http }}
              protocol: TCP
{{- if .Values.proxy.ssl.enabled }}
            - name: https
              containerPort: {{ .Values.proxy.ports.https }}
              protocol: TCP
{{- end }}
{{- if .Values.pod.probes.proxy.proxy.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.proxy.ports.http }}
              scheme: HTTP
{{ toYaml .Values.pod.probes.proxy.proxy.liveness.params | indent 12 }}
{{- end }}
{{- if .Values.pod.probes.proxy.proxy.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.proxy.ports.http }}
              scheme: HTTP
{{ toYaml .Values.pod.probes.proxy.proxy.readiness.params | indent 12 }}
{{- end }}
          volumeMounts:
            # PID 文件目录
            - name: nginx-run
              mountPath: /run
            # 默认配置文件
            - name: nexus-etc
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            # 配置文件目录
            - name: shared-config
              mountPath: /etc/nginx/conf.d
              subPath: nginx
              readOnly: true
{{- if .Values.proxy.ssl.enabled }}
            # SSL 证书目录
            - name: shared-config
              mountPath: /etc/nginx/ssl
              subPath: ssl
              readOnly: true
{{- end }}
          env:
            - name: PORT_HTTP
              value: {{ .Values.proxy.ports.http | quote }}
            - name: PORT_HTTPS
              value: {{ .Values.proxy.ports.https | quote }}
      volumes:
        - name: nginx-run
          emptyDir: {}
        - name: nexus-etc
          configMap:
            name: nexus-etc
            defaultMode: 0444
        - name: shared-config
          persistentVolumeClaim:
            claimName: nexus-shared-config
{{- end }}