{{/*
Licensed under the Apache License, Version 2.0 (the "License");
*/}}

{{- if .Values.manifests.secret_keystone }}
{{- $envAll := . }}
{{- range $key1, $userClass := tuple "admin" "nexus" }}
{{- $secretName := index $envAll.Values.secrets.identity $userClass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
{{ tuple $envAll "nexus" "keystone-credential" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
type: Opaque
data:
{{- $userDetails := index $envAll.Values.endpoints.identity.auth $userClass }}
{{- range $key2, $value := $userDetails }}
  {{ $key2 | upper }}: {{ $value | b64enc }}
{{- end }}
  OS_AUTH_URL: {{ tuple "identity" "internal" "api" $envAll | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup" | b64enc }}
  OS_IDENTITY_API_VERSION: {{ "3" | b64enc }}
{{- end }}
{{- end }}