{{/*
Licensed under the Apache License, Version 2.0 (the "License");
*/}}

{{- if and .Values.manifests.service_dns .Values.dns.enabled }}
{{- $envAll := . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ tuple "dns" "public" . | include "helm-toolkit.endpoints.hostname_short_endpoint_lookup" }}
  labels:
{{ tuple $envAll "nexus" "dns" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{- if .Values.dns.loadbalancer_ip }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.dns.loadbalancer_ip }}
  {{- end }}
spec:
  type: {{ .Values.dns.service_type }}
  {{- if .Values.dns.loadbalancer_ip }}
  loadBalancerIP: {{ .Values.dns.loadbalancer_ip }}
  {{- end }}
  ports:
    - name: dns-udp
      port: {{ .Values.dns.port }}
      targetPort: dns-udp
      protocol: UDP
    - name: dns-tcp
      port: {{ .Values.dns.port }}
      targetPort: dns-tcp
      protocol: TCP
  selector:
{{ tuple $envAll "nexus" "dns" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  {{- if eq .Values.dns.service_type "LoadBalancer" }}
  externalTrafficPolicy: Local
  {{- end }}
{{- end }}