---
pod:
  security_context:
    server:
      container:
        prometheus_alertmanager:
          appArmorProfile:
            type: RuntimeDefault
        prometheus_alertmanager_perms:
          appArmorProfile:
            type: RuntimeDefault
        apache_proxy:
          appArmorProfile:
            type: RuntimeDefault
    kubernetes_entrypoint:
      container:
        kubernetes_entrypoint:
          appArmorProfile:
            type: RuntimeDefault
...
