{
 "title": "Incus",
 "description": "Overview of Incus instances",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(incus_procs_total, job)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(incus_procs_total{job=\"$job\"}, project)"
    }
   },
   {
    "name": "name",
    "label": "Instance",
    "query": {
     "query": "label_values(incus_procs_total{job=\"$job\",project=\"$project\"}, name)"
    }
   },
   { "name": "top", "label": "Top", "query": "3, 4, 5, 10, 15, 20" }
  ]
 },
 "panels": [
  { "title": "Project overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top ${top} CPU usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, sum by (name) (increase(incus_cpu_seconds_total{mode!=\"idle\",job=\"$job\",project=\"$project\"}[$__range])))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(increase(incus_cpu_seconds_total{mode!=\"idle\",job=\"$job\",project=\"$project\"}[$__range])) - sum(topk(${top}, sum by (name) (increase(incus_cpu_seconds_total{mode!=\"idle\",job=\"$job\",project=\"$project\"}[$__range]))))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Top ${top} memory usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, incus_memory_MemTotal_bytes{job=\"$job\",project=\"$project\"} - incus_memory_MemFree_bytes - incus_memory_Cached_bytes)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(incus_memory_MemTotal_bytes{job=\"$job\",project=\"$project\"} - incus_memory_MemFree_bytes - incus_memory_Cached_bytes) -\nsum(topk(${top}, incus_memory_MemTotal_bytes{job=\"$job\",project=\"$project\"} - incus_memory_MemFree_bytes - incus_memory_Cached_bytes))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Top ${top} rootfs usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, incus_filesystem_size_bytes{job=\"$job\",project=\"$project\",mountpoint=\"/\"} - incus_filesystem_avail_bytes)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(incus_filesystem_size_bytes{job=\"$job\",project=\"$project\",mountpoint=\"/\"} - incus_filesystem_avail_bytes) - \nsum(topk(${top}, incus_filesystem_size_bytes{job=\"$job\",project=\"$project\",mountpoint=\"/\"} - incus_filesystem_avail_bytes))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "stat",
   "description": "Total disk reads during the time interval",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(incus_disk_read_bytes_total{job=\"$job\",project=\"$project\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "stat",
   "description": "Total disk writes during the time interval",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(incus_disk_written_bytes_total{job=\"$job\",project=\"$project\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Network RX",
   "type": "stat",
   "description": "Total network RX traffic during the time interval",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(incus_network_receive_bytes_total{job=\"$job\",project=\"$project\"}[$__range]))*8"
    }
   ]
  },
  {
   "title": "Network TX",
   "type": "stat",
   "description": "Total network TX traffic during the time interval",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(incus_network_transmit_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__range]))*8"
    }
   ]
  },
  {
   "title": "Top ${top} network TX traffic usage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, sum by (name) (rate(incus_network_transmit_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(incus_network_transmit_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval])*8) -\nsum(topk(${top}, sum by (name) (rate(incus_network_transmit_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Top ${top} network RX traffic usage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, sum by (name) (rate(incus_network_receive_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(incus_network_receive_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval])*8) -\nsum(topk(${top}, sum by (name) (rate(incus_network_receive_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Top ${top} network TX packets/s usage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, sum by (name) (rate(incus_network_transmit_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(incus_network_transmit_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval])*8) -\nsum(topk(${top}, sum by (name) (rate(incus_network_transmit_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Top ${top} network RX packets/s usage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, sum by (name) (rate(incus_network_receive_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum(rate(incus_network_receive_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval])*8) -\nsum(topk(${top}, sum by (name) (rate(incus_network_receive_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8))",
     "legendFormat": "Others"
    }
   ]
  },
  {
   "title": "Project CPU Usage",
   "type": "timeseries",
   "description": "CPU usage overview for the whole project",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(incus_cpu_seconds_total{mode!=\"idle\",job=\"$job\",project=\"$project\"}[$__rate_interval])) by (mode) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Project Memory Usage",
   "type": "timeseries",
   "description": "Memory usage overview for the whole project",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(incus_memory_MemTotal_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "sum(incus_memory_MemTotal_bytes{job=\"$job\",project=\"$project\"} - incus_memory_MemFree_bytes - incus_memory_Cached_bytes)",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "sum(incus_memory_Cached_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "sum(incus_memory_MemFree_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "sum(incus_memory_Swap_bytes{job=\"$job\",project=\"$project\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Project Running Processes",
   "type": "timeseries",
   "description": "Number of running processes for the whole project",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(incus_procs_total{job=\"$job\",project=\"$project\"})",
     "legendFormat": "Processes"
    }
   ]
  },
  {
   "title": "Project Disk Space Usage (rootfs)",
   "type": "timeseries",
   "description": "Disk space used for the whole project",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(incus_filesystem_size_bytes{mountpoint=\"/\",job=\"$job\",project=\"$project\"} - incus_filesystem_avail_bytes)",
     "legendFormat": "Disk used"
    },
    {
     "expr": "sum(incus_filesystem_size_bytes{mountpoint=\"/\",job=\"$job\",project=\"$project\"})",
     "legendFormat": "Disk quota"
    }
   ]
  },
  {
   "title": "Project Disk R/W Data",
   "type": "timeseries",
   "description": "The number of bytes read or written per second for the whole project",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(incus_disk_written_bytes_total{job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "Written bytes"
    },
    {
     "expr": "sum(rate(incus_disk_read_bytes_total{job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "Read bytes"
    }
   ]
  },
  {
   "title": "Project Disk IO/s",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the whole project",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(incus_disk_writes_completed_total{job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "Writes completed"
    },
    {
     "expr": "sum(rate(incus_disk_reads_completed_total{job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "Reads completed"
    }
   ]
  },
  {
   "title": "Project Network Traffic",
   "type": "timeseries",
   "description": "Network traffic overview for the whole project",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(incus_network_transmit_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(rate(incus_network_receive_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))*8",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Project Network Packets/s",
   "type": "timeseries",
   "description": "Network traffic overview for the whole project",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(incus_network_transmit_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "TX"
    },
    {
     "expr": "sum(rate(incus_network_receive_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Project Network Errors & Drops",
   "type": "timeseries",
   "description": "Network errors and drop overview for the whole project",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(incus_network_receive_errs_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "RX errors"
    },
    {
     "expr": "sum(rate(incus_network_transmit_errs_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "TX errors"
    },
    {
     "expr": "sum(rate(incus_network_receive_drop_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "RX drop"
    },
    {
     "expr": "sum(rate(incus_network_transmit_drop_total{device!=\"lo\",job=\"$job\",project=\"$project\"}[$__rate_interval]))",
     "legendFormat": "TX drop"
    }
   ]
  },
  {
   "title": "Instance: $name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "repeat": "name",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(incus_cpu_seconds_total{mode!=\"idle\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])) by (mode) * 100",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(incus_memory_MemTotal_bytes{job=\"$job\",project=\"$project\",name=\"$name\"})",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "sum(incus_memory_MemTotal_bytes{job=\"$job\",project=\"$project\",name=\"$name\"} - incus_memory_MemFree_bytes - incus_memory_Cached_bytes)",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "sum(incus_memory_Cached_bytes{job=\"$job\",project=\"$project\",name=\"$name\"})",
       "legendFormat": "RAM Cache"
      },
      {
       "expr": "sum(incus_memory_MemFree_bytes{job=\"$job\",project=\"$project\",name=\"$name\"})",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "sum(incus_memory_Swap_bytes{job=\"$job\",project=\"$project\",name=\"$name\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Running Processes",
     "type": "timeseries",
     "description": "Number of running processes in the instance",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "incus_procs_total{job=\"$job\",project=\"$project\",name=\"$name\"}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "timeseries",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((incus_filesystem_avail_bytes{job=\"$job\",project=\"$project\",name=\"$name\"} * 100) / incus_filesystem_size_bytes)",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Disk R/W Data",
     "type": "timeseries",
     "description": "The number of bytes read from or written to the device per second",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(incus_disk_written_bytes_total{job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Written bytes"
      },
      {
       "expr": "rate(incus_disk_read_bytes_total{job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Read bytes"
      }
     ]
    },
    {
     "title": "Disk IO/s",
     "type": "timeseries",
     "description": "The number (after merges) of I/O requests completed per second for the device",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(incus_disk_writes_completed_total{job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Writes completed"
      },
      {
       "expr": "rate(incus_disk_reads_completed_total{job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - Reads completed"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(incus_network_transmit_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - TX"
      },
      {
       "expr": "rate(incus_network_receive_bytes_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])*8",
       "legendFormat": "{{device}} - RX"
      }
     ]
    },
    {
     "title": "Network Packets/s",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(incus_network_transmit_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
       "legendFormat": "TX {{device}}"
      },
      {
       "expr": "rate(incus_network_receive_packets_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
       "legendFormat": "RX {{device}}"
      }
     ]
    },
    {
     "title": "Network Errors & Drops",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(incus_network_receive_errs_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - RX errors"
      },
      {
       "expr": "rate(incus_network_transmit_errs_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - TX errors"
      },
      {
       "expr": "rate(incus_network_receive_drop_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - RX drop"
      },
      {
       "expr": "rate(incus_network_transmit_drop_total{device!=\"lo\",job=\"$job\",project=\"$project\",name=\"$name\"}[$__rate_interval])",
       "legendFormat": "{{device}} - TX drop"
      }
     ]
    }
   ]
  },
  { "title": "Loki logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } }
 ]
}