{{/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.configmap_net }}
{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: octavia-net
  namespace: {{ .Release.Namespace }}
  labels:
{{ tuple $envAll "octavia" "network-config" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
  annotations:
{{ tuple $envAll | include "helm-toolkit.snippets.release_uuid" | indent 4 }}
data:
  # =====================================
  # 管理网络配置参数（可手动修改后重新运行 Job）
  # 支持 flat, vlan, vxlan 三种网络模式
  # =====================================

  # 网络模式配置
  network_type: {{ .Values.network.management.network_type | quote }}

  # 网络设备和提供者网络
  device: {{ .Values.network.management.device | quote }}
  provider_network: {{ .Values.network.management.provider_network | quote }}

  # 网络和子网名称
  network_name: {{ .Values.network.management.network_name | quote }}
  subnet_name: {{ .Values.network.management.subnet_name | quote }}

  # 网络类型相关配置
  {{- if .Values.network.management.vlan_id }}
  vlan_id: {{ .Values.network.management.vlan_id | quote }}
  {{- end }}
  {{- if .Values.network.management.segmentation_id }}
  segmentation_id: {{ .Values.network.management.segmentation_id | quote }}
  {{- end }}

  # 子网配置
  subnet_cidr: {{ .Values.network.management.subnet_cidr | quote }}
  subnet_alloc_start: {{ .Values.network.management.subnet_alloc_start | quote }}
  subnet_alloc_end: {{ .Values.network.management.subnet_alloc_end | quote }}

  # 网关配置（可选）
  {{- if .Values.network.management.subnet_gateway }}
  subnet_gateway: {{ .Values.network.management.subnet_gateway | quote }}
  {{- end }}

  # DNS 服务器配置（可选）
  {{- if .Values.network.management.subnet_dns_server }}
  subnet_dns_server: {{ .Values.network.management.subnet_dns_server | quote }}
  {{- end }}

  # 网络属性配置
  {{- if .Values.network.management.mtu }}
  mtu: {{ .Values.network.management.mtu | quote }}
  {{- end }}

  # 高级选项
  {{- if .Values.network.management.enable_dhcp }}
  enable_dhcp: {{ .Values.network.management.enable_dhcp | quote }}
  {{- end }}
  {{- if .Values.network.management.shared }}
  shared: {{ .Values.network.management.shared | quote }}
  {{- end }}

  # SSH 密钥配置
  ssh_key_name: {{ .Values.conf.octavia.controller_worker.amp_ssh_key_name | quote }}
{{- end }}