---
# Copyright 2018, SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    templates:
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-helm-linter
        - openstack-helm-bandit
        # 2023.2
        - openstack-helm-cinder-2023-2-ubuntu_jammy  # 5 nodes rook
        - openstack-helm-compute-kit-2023-2-ubuntu_jammy  # 3 nodes
        - openstack-helm-compute-kit-ovn-2023-2-ubuntu_jammy  # 3 nodes
        # 2024.1
        - openstack-helm-keystone-ldap-2023-2-ubuntu_jammy  # 1 node
        - openstack-helm-tls-2024-1-ubuntu_jammy  # 3 nodes rook
        - openstack-helm-cinder-2024-1-ubuntu_jammy  # 5 nodes rook
        - openstack-helm-compute-kit-2024-1-ubuntu_jammy  # 3 nodes
        - openstack-helm-compute-kit-metallb-2024-1-ubuntu_jammy  # 1 node + 3 nodes
        - openstack-helm-compute-kit-cilium-metallb-2024-1-ubuntu_jammy  # 1 node + 3 nodes
        - openstack-helm-horizon-2024-1-ubuntu_jammy  # 1 node
        - openstack-helm-tacker-2024-1-ubuntu_jammy
        - openstack-helm-compute-kit-dpdk-2024-1-ubuntu_jammy  # 32GB node
        # 2024.2
        - openstack-helm-cinder-2024-2-ubuntu_jammy  # 3 nodes rook
        - openstack-helm-compute-kit-2024-2-ubuntu_jammy  # 1 node + 3 nodes
        # Infra jobs
        - openstack-helm-logging
        - openstack-helm-monitoring
        - openstack-helm-metacontroller
        - openstack-helm-mariadb-operator-2024-1-ubuntu_jammy
    gate:
      jobs:
        - openstack-helm-linter
        - openstack-helm-cinder-2024-1-ubuntu_jammy
        - openstack-helm-compute-kit-2024-1-ubuntu_jammy
        - openstack-helm-logging
        - openstack-helm-monitoring
        - openstack-helm-metacontroller
    post:
      jobs:
        - openstack-helm-publish-charts
    # periodic:
    #   jobs:
    #     - openstack-helm-compute-kit-helm-repo-public-2024-1-ubuntu_jammy  # 1 node + 2 nodes
    #     - openstack-helm-compute-kit-rook-2024-1-ubuntu_jammy  # 5 nodes / rook
    periodic-weekly:
      jobs:
        - openstack-helm-ceph-migrate
...
