---
pod:
  security_context:
    api:
      container:
        prometheus:
          appArmorProfile:
            type: RuntimeDefault
        prometheus_perms:
          appArmorProfile:
            type: RuntimeDefault
        apache_proxy:
          appArmorProfile:
            type: RuntimeDefault
    test:
      container:
        prometheus_helm_tests:
          appArmorProfile:
            type: RuntimeDefault
    kubernetes_entrypoint:
      container:
        kubernetes_entrypoint:
          appArmorProfile:
            type: RuntimeDefault
...
