---
spec:
  template:
    spec:
      containers:
        - name: calico-node
          env:
            # we need Calico to skip this interface while discovering the
            # network changes on the host to prevent announcing unnecessary networks.
            - name: IP_AUTODETECTION_METHOD
              value: "skip-interface=br-ex|provider.*|client.*|o-hm.*|o-w.*"
...
